#%RAML 1.0
baseUri: http://ms3-rangeencoder.cloudhub.io/api/ # 
version: v1

title: EncodedRangeAPI
types: 
  EncodedRange: !include types/EncodedRangeType.raml

/EncodedRange:
  get:
    queryParameters: 
      startValue:  
        required: true
        type: integer
      endValue:  
        required: true
        type: integer
      reversed:
        required: false
        type: boolean
    responses: 
      200:
        body: 
          application/json:
            type: EncodedRange
            example: !include examples/EncodedRange_example.json
